#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2018-09-28 21:35:35 +0100 (Fri, 28 Sep 2018)
#
#  https://github.com/harisekhon/haproxy-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

# there's no 'language: bash'
language: generic

sudo: false

notifications:
  email: false

install:
  - apt-get install -y haproxy
  - ./check_haproxy_syntax.sh

#script:
#  - travis_retry make test
